/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calcPack;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;

/**
 *
 * @author G50
 */
public class calcFrame extends javax.swing.JFrame {
  int pX, pY,cpX, cpY;
    /**
     * Creates new form calcFrame
     */
    public calcFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        btn8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn7 = new javax.swing.JLabel();
        btn9 = new javax.swing.JLabel();
        btn4 = new javax.swing.JLabel();
        btn5 = new javax.swing.JLabel();
        btn6 = new javax.swing.JLabel();
        btn1 = new javax.swing.JLabel();
        btn2 = new javax.swing.JLabel();
        btn3 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        btn0 = new javax.swing.JLabel();
        btnDot = new javax.swing.JLabel();
        btnEquals = new javax.swing.JLabel();
        btnPlus = new javax.swing.JLabel();
        btnMultiply = new javax.swing.JLabel();
        btnDivide = new javax.swing.JLabel();
        fld = new javax.swing.JTextField();
        ground = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 404));
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn8MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn8MousePressed(evt);
            }
        });
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 60, 60));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 130, 30));

        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn7MousePressed(evt);
            }
        });
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, 60));

        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn9MousePressed(evt);
            }
        });
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, 60));

        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn4MousePressed(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 60));

        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn5MousePressed(evt);
            }
        });
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 60, 60));

        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn6MousePressed(evt);
            }
        });
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 60, 60));

        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn1MousePressed(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 50, 50));

        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn2MousePressed(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 60, 60));

        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn3MousePressed(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 60, 60));

        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelMousePressed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 70, 60));

        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn0MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn0MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn0MousePressed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 60, 60));

        btnDot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDotMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDotMousePressed(evt);
            }
        });
        getContentPane().add(btnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 60, 50));

        btnEquals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEqualsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEqualsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEqualsMousePressed(evt);
            }
        });
        getContentPane().add(btnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 60, 60));

        btnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPlusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPlusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPlusMousePressed(evt);
            }
        });
        getContentPane().add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 60, 100));

        btnMultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMultiplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMultiplyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMultiplyMousePressed(evt);
            }
        });
        getContentPane().add(btnMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 70, 60));

        btnDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDivideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDivideMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDivideMousePressed(evt);
            }
        });
        getContentPane().add(btnDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 70, 70));

        fld.setEditable(false);
        fld.setBackground(new java.awt.Color(255, 255, 255));
        fld.setFont(new java.awt.Font("Microsoft JhengHei", 0, 36)); // NOI18N
        fld.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fld.setBorder(null);
        getContentPane().add(fld, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 70));

        ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png"))); // NOI18N
        getContentPane().add(ground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/exit.png"))); // NOI18N
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png"))); // NOI18N
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void btn7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseEntered
    ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/7.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseEntered

    private void btn7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseExited
  ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MouseExited

    private void btn7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MousePressed
String xxx=fld.getText();
xxx=xxx+"7";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7MousePressed

    private void btn8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseEntered
    ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/8.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseEntered

    private void btn8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseExited
    ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));    // TODO add your handling code here:
    }//GEN-LAST:event_btn8MouseExited

    private void btn8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MousePressed
String xxx=fld.getText();
xxx=xxx+"8";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn8MousePressed

    private void btn9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseEntered
   ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/9.png")));     // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseEntered

    private void btn9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseExited
   ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));     // TODO add your handling code here:
    }//GEN-LAST:event_btn9MouseExited

    private void btn9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MousePressed
String xxx=fld.getText();
xxx=xxx+"9";
fld.setText(xxx);        
// TODO add your handling code here:
    }//GEN-LAST:event_btn9MousePressed

    private void btn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseEntered
      ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/4.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_btn4MouseEntered

    private void btn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseExited
     ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));   // TODO add your handling code here:
    }//GEN-LAST:event_btn4MouseExited

    private void btn4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MousePressed
       String xxx=fld.getText();
xxx=xxx+"4";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn4MousePressed

    private void btn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseEntered
        ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/5.png")));// TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseEntered

    private void btn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseExited
    ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));    // TODO add your handling code here:
    }//GEN-LAST:event_btn5MouseExited

    private void btn5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MousePressed
      String xxx=fld.getText();
xxx=xxx+"5";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn5MousePressed

    private void btn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseEntered
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/6.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btn6MouseEntered

    private void btn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseExited
      ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_btn6MouseExited

    private void btn6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MousePressed
      String xxx=fld.getText();
xxx=xxx+"6";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6MousePressed

    private void btn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseEntered
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/1.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btn1MouseEntered

    private void btn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseExited
        ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));// TODO add your handling code here:
    }//GEN-LAST:event_btn1MouseExited

    private void btn1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MousePressed
     String xxx=fld.getText();
xxx=xxx+"1";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1MousePressed

    private void btn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseEntered
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/2.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseEntered

    private void btn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseExited
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btn2MouseExited

    private void btn2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MousePressed
      String xxx=fld.getText();
xxx=xxx+"2";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2MousePressed

    private void btn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseEntered
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/3.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseEntered

    private void btn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseExited
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btn3MouseExited

    private void btn3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MousePressed
      String xxx=fld.getText();
xxx=xxx+"3";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3MousePressed

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/clear.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
      ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMousePressed
fld.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelMousePressed

    private void btn0MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseEntered
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/0.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btn0MouseEntered

    private void btn0MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseExited
      ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_btn0MouseExited

    private void btn0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MousePressed
String xxx=fld.getText();
xxx=xxx+"0";
fld.setText(xxx);        
// TODO add your handling code here:
    }//GEN-LAST:event_btn0MousePressed

    private void btnDotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseEntered
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/dot.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btnDotMouseEntered

    private void btnDotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMouseExited
        ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));// TODO add your handling code here:
    }//GEN-LAST:event_btnDotMouseExited

    private void btnDotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDotMousePressed
   String xxx=fld.getText();
xxx=xxx+".";
fld.setText(xxx); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDotMousePressed

    private void btnEqualsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualsMouseEntered
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/equals.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btnEqualsMouseEntered

    private void btnEqualsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualsMouseExited
     ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));   // TODO add your handling code here:
    }//GEN-LAST:event_btnEqualsMouseExited

    private void btnEqualsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEqualsMousePressed
ScriptEngineManager SEM=new ScriptEngineManager();
ScriptEngine SE= SEM.getEngineByName("JavaScript");
try{
   fld.setText(SE.eval(fld.getText()).toString());
}catch(Exception e){
    
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnEqualsMousePressed

    private void btnPlusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMouseEntered
     ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/add.png")));   // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusMouseEntered

    private void btnPlusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMouseExited
       ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusMouseExited

    private void btnPlusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMousePressed
      String xxx=fld.getText();
xxx=xxx+"+";
fld.setText(xxx); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusMousePressed

    private void btnDivideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMouseEntered
  ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/devide.png")));      // TODO add your handling code here:
    }//GEN-LAST:event_btnDivideMouseEntered

    private void btnDivideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMouseExited
ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivideMouseExited

    private void btnMultiplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplyMouseEntered
   ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/multiply.png")));     // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplyMouseEntered

    private void btnMultiplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplyMouseExited
  ground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcStore/back.png")));      // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplyMouseExited

    private void btnMultiplyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplyMousePressed
    String xxx=fld.getText();
xxx=xxx+"*";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplyMousePressed

    private void btnDivideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivideMousePressed
    String xxx=fld.getText();
xxx=xxx+"/";
fld.setText(xxx);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDivideMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
      pX = evt.getX();
        pY = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       this.setLocation(this.getLocation().x + evt.getX() - pX, this.getLocation().y + evt.getY() - pY);
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn0;
    private javax.swing.JLabel btn1;
    private javax.swing.JLabel btn2;
    private javax.swing.JLabel btn3;
    private javax.swing.JLabel btn4;
    private javax.swing.JLabel btn5;
    private javax.swing.JLabel btn6;
    private javax.swing.JLabel btn7;
    private javax.swing.JLabel btn8;
    private javax.swing.JLabel btn9;
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnDivide;
    private javax.swing.JLabel btnDot;
    private javax.swing.JLabel btnEquals;
    private javax.swing.JLabel btnMultiply;
    private javax.swing.JLabel btnPlus;
    private javax.swing.JTextField fld;
    private javax.swing.JLabel ground;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
